config/routes.rb
Rails.application.routes.draw do
  resources :departments do
    resources :courses do
      resources :coursegoals
    end
    resources :deptgoals
  end
  resources :instgoals
  get "/", to: "homepage#home", as: "root"
  get "/about", to: "homepage#about"
  get "/contact", to: "homepage#contact"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :department
end

app/models/coursegoal.rb
class Coursegoal < ApplicationRecord
  belongs_to :deptgoal
  belongs_to :course
end

app/models/department.rb
class Department < ApplicationRecord
  def to_param
    deptCode
  end
end

app/models/deptgoal.rb
class Deptgoal < ApplicationRecord
  belongs_to :instgoal
  belongs_to :department
end

app/models/instgoal.rb
class Instgoal < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def hello
    render html: "hello world"
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :get_dept, only: [:show, :edit, :update, :destroy, :index]

  def index
    @courses = Course.where(department: @department)
  end

  def show
    @coursegoals = Coursegoal.where(course: @course)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def get_dept
      @department = Department.find_by(deptCode: params[:department_id])
    end

    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    #def course_params
    #  params.require(:course).permit(:goalNum, :goalText, :goalDetails, :text)
    #end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
    @deptgoals = Deptgoal.where(department: @department).order(:goalNum)
    @courses = Course.where(department: @department)
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      #this is not really ideal.
      #ideally it would be something like @department = Department.find(params[:deptCode]) but that doesn't work.
      #if a future group is seeing this feel free to email me at munsenab[@]grinnell.edu for an explanation.
      @department = Department.find_by(deptCode: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:deptSubject, :deptFullName, :deptCode)
    end
end

app/controllers/deptgoals_controller.rb
class DeptgoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]
  before_action :get_dept, only: [:show, :edit, :update, :destroy, :index]

  #def index
  #  @deptgoals = Deptgoal.where(department: @department)
  #end

  def show
    @coursegoals = Coursegoal.where(deptgoal: @deptgoal)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def get_dept
      @department = Department.find_by(deptCode: params[:department_id])
    end

    def set_goal
      @deptgoal = Deptgoal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    #def course_params
    #  params.require(:course).permit(:goalNum, :goalText, :goalDetails, :text)
    #end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

end

app/controllers/instgoals_controller.rb
class InstgoalsController < ApplicationController
  before_action :set_instgoal, only: [:show, :edit, :update, :destroy]

  # GET /instgoals
  # GET /instgoals.json
  def index
    @instgoals = Instgoal.all
  end

  # GET /instgoals/1
  # GET /instgoals/1.json
  def show
    @deptgoals = Deptgoal.where(instgoal: @instgoal)
  end

  # GET /instgoals/new
  def new
    @instgoal = Instgoal.new
  end

  # GET /instgoals/1/edit
  def edit
  end

  # POST /instgoals
  # POST /instgoals.json
  def create
    @instgoal = Instgoal.new(instgoal_params)

    respond_to do |format|
      if @instgoal.save
        format.html { redirect_to @instgoal, notice: 'Instgoal was successfully created.' }
        format.json { render :show, status: :created, location: @instgoal }
      else
        format.html { render :new }
        format.json { render json: @instgoal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instgoals/1
  # PATCH/PUT /instgoals/1.json
  def update
    respond_to do |format|
      if @instgoal.update(instgoal_params)
        format.html { redirect_to @instgoal, notice: 'Instgoal was successfully updated.' }
        format.json { render :show, status: :ok, location: @instgoal }
      else
        format.html { render :edit }
        format.json { render json: @instgoal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instgoals/1
  # DELETE /instgoals/1.json
  def destroy
    @instgoal.destroy
    respond_to do |format|
      format.html { redirect_to instgoals_url, notice: 'Instgoal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instgoal
      @instgoal = Instgoal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instgoal_params
      params.require(:instgoal).permit(:goalNum, :goalText, :goalDetails, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/deptgoals_helper.rb
module DeptgoalsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/instgoals_helper.rb
module InstgoalsHelper
end

app/views/courses/index.html.erb
<% provide(:title, "Courses") %>
<h1><%="#{@department.deptSubject} Courses"%></h1>

<table>
  <thead>
    <tr>
      <th>Courses</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.courseTitle %></td>
        <td><%= link_to 'Show', [course.department, course] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/courses/show.html.erb
<% provide(:title, "#{@course.courseCode}") %>

<h1><%= @course.courseTitle %></h1>
<h2><%= "#{@department.deptCode}-#{@course.courseCode}-#{@course.courseSection}" %></h2>

<p>
  <strong>Course Details:</strong>
  <%= @course.courseDetails %>
</p>

<h2>Course Goals</h2>
<table>
    <% @coursegoals.each do |goal| %>
      <tr>
        <td><%= goal.goalNum %></td>
        <td><%= goal.goalText %></td>
      </tr>
    <% end %>
</table>

app/views/departments/_form.html.erb
<%= form_with(model: department, local: true) do |form| %>
  <% if department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% department.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :deptSubject %>
    <%= form.text_field :deptSubject %>
  </div>

  <div class="field">
    <%= form.label :deptFullName %>
    <%= form.text_field :deptFullName %>
  </div>

  <div class="field">
    <%= form.label :deptCode %>
    <%= form.text_field :deptCode %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing Department</h1>

<%= render 'form', department: @department %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

app/views/departments/index.html.erb
<% provide(:title, "Departments") %>
<h1>Departments</h1>

<table>
  <thead>
    <tr>
      <th>Department</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= department.deptFullName %></td>
        <td><%= link_to 'Show', department %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/departments/new.html.erb
<h1>New Department</h1>

<%= render 'form', department: @department %>

<%= link_to 'Back', departments_path %>

app/views/departments/show.html.erb
<% provide(:title, "#{@department.deptSubject}") %>

<h1><%= @department.deptFullName %></h1>

<h2>Department Goals</h2>
<table>
    <% @deptgoals.each do |goal| %>
      <tr>
        <td><%= goal.goalNum %></td>
        <td><%= goal.goalText %></td>
        <td><%= link_to 'Show', [goal.department, goal] %></td>
      </tr>
    <% end %>
</table>

<h2>Department Courses</h2>
<table>
    <% @courses.each do |course| %>
      <tr>
        <td><%= "#{@department.deptCode}#{course.courseCode}-#{course.courseSection}" %></td>
        <td><%= course.courseTitle %></td>
        <td><%= link_to 'Show', [course.department, course] %></td>
      </tr>
    <% end %>
</table>

<%= link_to 'All departments', departments_path %>

app/views/deptgoals/show.html.erb
<% provide(:title, "#{@department.deptFullName} Goal #{@deptgoal.goalNum}") %>

<h1><%= "#{@department.deptFullName} Goal #{@deptgoal.goalNum}" %></h1>
<h2><%= @deptgoal.goalText %> </h2>
<p><%= @deptgoal.goalDetails %> </p>

<h2>Courses with goals corresponding to this one</h2>
<table>
    <% @coursegoals.each do |goal| %>
      <tr>
        <td><%= "#{@department.deptCode}#{goal.course.courseCode}-#{goal.course.courseSection}" %></td>
        <td><%= goal.course.semester%></td>
        <td><%= goal.goalText %></td>
        <td><%= link_to 'Show', [goal.course.department, goal.course] %></td>
      </tr>
    <% end %>
</table>

app/views/homepage/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <h1><%= yield(:title) %></h1>
    <p>
      The Center for Teaching, Learning, and Assessment (CTLA) is dedicated to the mission of enhancing the success of the interactions between teachers and learners by supporting teachers as learners of pedagogy, technology, and assessment in the service of promoting excellent education in the liberal arts.
    </p>
    <p>
      The CTLA's mission is accomplished by the expansion and advancement of faculty development opportunities, the facilitation of teaching techniques using instructional technology, and the advancement of educational skills through the support of learning laboratories in reading, science, math, and writing for students.
    </p>
  </body>
</html>

app/views/homepage/contact.html.erb
<% provide(:title, "Contact") %>
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <h1><%= yield(:title) %></h1>
    <p>
      WIP
    </p>
  </body>
</html>

app/views/homepage/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <h1>Home</h1>
    This website shows connections between Grinnell's goals on the institutional, departmental, and course levels.
  </body>
</html>

app/views/instgoals/_form.html.erb
<%= form_with(model: instgoal, local: true) do |form| %>
  <% if instgoal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instgoal.errors.count, "error") %> prohibited this instgoal from being saved:</h2>

      <ul>
      <% instgoal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :goalNum %>
    <%= form.number_field :goalNum %>
  </div>

  <div class="field">
    <%= form.label :goalText %>
    <%= form.text_area :goalText %>
  </div>

  <div class="field">
    <%= form.label :goalDetails %>
    <%= form.text_field :goalDetails %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/instgoals/edit.html.erb
<h1>Editing Instgoal</h1>

<%= render 'form', instgoal: @instgoal %>

<%= link_to 'Show', @instgoal %> |
<%= link_to 'Back', instgoals_path %>

app/views/instgoals/index.html.erb
<% provide(:title, "Institutional Goals") %>
<h1>Institutional Goals</h1>

<table>
  <thead>
    <tr>
      <th colspan="2">Goal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instgoals.each do |instgoal| %>
      <tr>
        <td><%= instgoal.goalNum %></td>
        <td><%= instgoal.goalText %></td>
        <td><%= link_to 'Show', instgoal %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/instgoals/new.html.erb
<h1>New Instgoal</h1>

<%= render 'form', instgoal: @instgoal %>

<%= link_to 'Back', instgoals_path %>

app/views/instgoals/show.html.erb
<% provide(:title, "Institutional Goal #{@instgoal.goalNum}") %>

<h1>Institutional Goal <%= @instgoal.goalNum %></h1>

<h2><%= @instgoal.goalText %></h2>

<p>
  <strong>Goal Details:</strong>
  <%= @instgoal.goalDetails %>
</p>

<h2>Departments with goals corresponding to this one</h2>
<table>
    <% @deptgoals.each do |goal| %>
      <tr>
        <td><%= goal.department.deptSubject %></td>
        <td><%= goal.goalText %></td>
        <td><%= link_to 'Show', goal.department %></td>
      </tr>
    <% end %>
</table>

<%= link_to 'All institutional goals', instgoals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Grinnell Assessment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://use.typekit.net/cmx3oww.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track':
        'reload' %>
    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Grinnell College Assesment</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="/">Home</a></li>
      <li><a href="/about">About</a></li>
      <li><%= link_to "Institutional Goals", instgoals_path %> </li>
      <li><%= link_to "Department Goals", departments_path %> </li>
      <li><a href="/contact">Contact</a></li>
    </ul>
  </div>
    </nav>
     <div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8 main"> <%= yield %></div>
  <div class="col-sm-2"></div>
</div>
  </body>
</html>